### ISSUE TITLE
Cancel reader when read is blocking

### ISSUE THREAD

**Issue by ostcar** [dolmen-go/contextio#2]
I tried to solve a simular problem then your `reader`. But I work with streams, that can block for a long time. Here is a short example:

```go
func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	scanner := bufio.NewScanner(contextio.NewReader(ctx, os.Stdin))
	for scanner.Scan() {
		fmt.Println(scanner.Text())
	}
	if err := scanner.Err(); err != nil {
		log.Fatalf("Error reading from stdin: %v", err)
	}
}
```

This program is similar to `cat` but (should) stop after 5 seconds. Every line to type in stdin is printed back to stdout.

But if you stop typing before the 5 seconds are over, the program does not exists.

I don't know if this kind of problem is out of scope of tihs repo. For every one how is locking for a solution, here is a reader that stops a call to `Read()`, even when the input source is blocking:

```go
type reader struct {
	ctx context.Context
	r   io.Reader
}

func NewReader(ctx context.Context, r io.Reader) io.Reader {
	return &reader{ctx, r}
}

func (r *reader) Read(p []byte) (n int, err error) {
	wait := make(chan struct{})

	go func() {
		n, err = r.r.Read(p)
		close(wait)
	}()

	select {
	case <-wait:
	case <-r.ctx.Done():
		err = io.EOF
	}
	return n, err
}
```

**Comment by mholt** [comment]
Doesn't this leak the goroutine that calls Read() though? I don't see anything here that would (or possibly can) abort the underlying Read() call.

**Comment by ostcar** [comment]
That is true. But I don't know how else the problem could be solved.

How would you solve the case, that the call to r.Read() blocks for a longer time then the deadline from the context? See my initial example.

**Comment by mholt** [comment]
Probably close whatever it is reading from. But I do not know if/how that works in all cases. I don't know a surefire solution to the problem...
